### ISSUE TITLE
Views dependant on the Competition object association with the site should raise 404 if no Competition is available

### ISSUE THREAD

**Issue by rtrembecky** [tbabej/roots#22]
Internal Server Error: /sk/sutaze/semester/poradie/posledny/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/generic/detail.py", line 114, in get
    self.object = self.get_object()
  File "./competitions/views.py", line 185, in get_object
    return self.competition.season_set.order_by('-end')[0]
  File "./competitions/views.py", line 28, in competition
    return Competition.get_by_current_site()
  File "./competitions/models.py", line 61, in get_by_current_site
    return cls.get_by_site(Site.objects.get_current())
  File "./competitions/models.py", line 57, in get_by_site
    return cls.objects.get(site=site)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: Competition matching query does not exist.

**Comment by tbabej** [comment]
Fixed in master.
