### ISSUE TITLE
Internal Server Error: /sk/admin/problems/usersolution/6210/

### ISSUE THREAD

**Issue by rtrembecky** [tbabej/roots#23]
Internal Server Error: /sk/admin/problems/usersolution/6210/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/contrib/admin/options.py", line 583, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/var/www/roots-env/lib/python2.7/site-packages/reversion/revisions.py", line 297, in do_revision_context
    return func(*args, **kwargs)
  File "./base/util.py", line 87, in change_view
    object_id, form_url, extra_context=extra_context)
  File "/usr/lib64/python2.7/site-packages/django/contrib/admin/options.py", line 1456, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/usr/lib64/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib64/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/contrib/admin/options.py", line 1396, in changeform_view
    if form.is_valid():
  File "/usr/lib64/python2.7/site-packages/django/forms/forms.py", line 162, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/lib64/python2.7/site-packages/django/forms/forms.py", line 154, in errors
    self.full_clean()
  File "/usr/lib64/python2.7/site-packages/django/forms/forms.py", line 355, in full_clean
    self._post_clean()
  File "/usr/lib64/python2.7/site-packages/django/forms/models.py", line 422, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 990, in full_clean
    self.clean_fields(exclude=exclude)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 1032, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "./base/models.py", line 86, in clean
    file_obj = data.file
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/files.py", line 49, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "/usr/lib64/python2.7/site-packages/django/core/files/storage.py", line 35, in open
    return self._open(name, mode)
  File "/usr/lib64/python2.7/site-packages/django/core/files/storage.py", line 172, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/var/www/roots-env/roots/protected/solutions/z_Simona_Ducaiova-242.pdf'

Request repr():
<WSGIRequest
path:/sk/admin/problems/usersolution/6210/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'corrected_solution': [u''], u'solution': [u''], u'_continue': [u'Ulo\u017ei\u0165 a pokra\u010dova\u0165 v \xfaprav\xe1ch'], u'note': [u''], u'score': [u''], u'user': [u'557'], u'problem': [u'242'], u'csrfmiddlewaretoken': [u'9uogtFoqQQ0kCA64Bs36D6VPldERp0nx']}>,
COOKIES:{'csrftoken': '9uogtFoqQQ0kCA64Bs36D6VPldERp0nx',
 'sessionid': '3yc7qzqwernu6guetnoj5d1pnw2sn3mg'},
META:{'CONTENT_LENGTH': '994',
 'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryXi12B9SGrtQYv3Pr',
 u'CSRF_COOKIE': u'9uogtFoqQQ0kCA64Bs36D6VPldERp0nx',
 'DOCUMENT_ROOT': '/usr/share/nginx/html',
 'HTTPS': 'on',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_CACHE_CONTROL': 'max-age=0',
 'HTTP_CONTENT_LENGTH': '994',
 'HTTP_CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryXi12B9SGrtQYv3Pr',
 'HTTP_COOKIE': 'sessionid=3yc7qzqwernu6guetnoj5d1pnw2sn3mg; csrftoken=9uogtFoqQQ0kCA64Bs36D6VPldERp0nx',
 'HTTP_HOST': 'matik.strom.sk',
 'HTTP_ORIGIN': 'https://matik.strom.sk',
 'HTTP_REFERER': 'https://matik.strom.sk/sk/admin/problems/usersolution/6210/',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
 'PATH_INFO': u'/sk/admin/problems/usersolution/6210/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '88.212.46.89',
 'REMOTE_PORT': '51046',
 'REQUEST_METHOD': 'POST',
 'REQUEST_URI': '/sk/admin/problems/usersolution/6210/',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'matik.strom.sk',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.node': 'server.strom.sk',
 'uwsgi.version': '2.0.11.2',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7efc09ae1b70>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7efc07276f48>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>

**Comment by tbabej** [comment]
I believe this was due external factors (the file was really missing on the server and it should have been there). We should abort the opreration and display a proper error message to the user in this case.
