### ISSUE TITLE
Internal Server Error: /sk/ucty/facebook/login/

### ISSUE THREAD

**Issue by rtrembecky** [tbabej/roots#24]
Internal Server Error: /sk/ucty/facebook/login/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/roots-env/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 55, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/roots-env/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 78, in dispatch
    app = provider.get_app(self.request)
  File "/var/www/roots-env/lib/python2.7/site-packages/allauth/socialaccount/providers/base.py", line 36, in get_app
    return SocialApp.objects.get_current(self.id)
  File "/var/www/roots-env/lib/python2.7/site-packages/allauth/socialaccount/models.py", line 31, in get_current
    provider=provider)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: SocialApp matching query does not exist.

Request repr():
<WSGIRequest
path:/sk/ucty/facebook/login/,
GET:<QueryDict: {u'process': [u'login']}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': '',
 u'CSRF_COOKIE': u'BOJ31mUtNE67Ifc86AZokc6ldqpCGFiO',
 'DOCUMENT_ROOT': '/usr/share/nginx/html',
 'HTTPS': 'on',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip',
 'HTTP_HOST': 'zdruzenie.strom.sk',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)',
 'PATH_INFO': u'/sk/ucty/facebook/login/',
 'QUERY_STRING': 'process=login',
 'REMOTE_ADDR': '68.180.230.102',
 'REMOTE_PORT': '60671',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/sk/ucty/facebook/login/?process=login',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'zdruzenie.strom.sk',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.node': 'server.strom.sk',
 'uwsgi.version': '2.0.11.2',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7faba4684b70>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7faba3690e58>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>

**Comment by tbabej** [comment]
This is displayed if no social app is configured for the given site, we should probably catch the exception and raise 404, or skip offering social logging for that site.
