### ISSUE TITLE
Internal Server Error: /sk/priklady/odovzdaj/

### ISSUE THREAD

**Issue by rtrembecky** [tbabej/roots#26]
Internal Server Error: /sk/priklady/odovzdaj/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 104, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/middleware/csrf.py", line 174, in process_view
    request_csrf_token = request.POST.get('csrfmiddlewaretoken', '')
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/wsgi.py", line 135, in _get_post
    self._load_post_and_files()
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 233, in _load_post_and_files
    self._post, self._files = self.parse_file_upload(self.META, data)
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 198, in parse_file_upload
    return parser.parse()
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 205, in parse
    for chunk in field_stream:
  File "/usr/lib64/python2.7/site-packages/django/utils/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 344, in __next__
    output = next(self._producer)
  File "/usr/lib64/python2.7/site-packages/django/utils/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 475, in __next__
    for bytes in stream:
  File "/usr/lib64/python2.7/site-packages/django/utils/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 344, in __next__
    output = next(self._producer)
  File "/usr/lib64/python2.7/site-packages/django/utils/six.py", line 535, in next
    return type(self).__next__(self)
  File "/usr/lib64/python2.7/site-packages/django/http/multipartparser.py", line 406, in __next__
    data = self.flo.read(self.chunk_size)
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 267, in read
    six.reraise(UnreadablePostError, UnreadablePostError(*e.args), sys.exc_info()[2])
  File "/usr/lib64/python2.7/site-packages/django/http/request.py", line 265, in read
    return self._stream.read(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/wsgi.py", line 59, in read
    result = self.buffer + self._read_limited(size - len(self.buffer))
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/wsgi.py", line 47, in _read_limited
    result = self.stream.read(size)
UnreadablePostError: error during read(65536) on wsgi.input

Request repr():
<WSGIRequest
path:/sk/priklady/odovzdaj/,
GET:<QueryDict: {}>,
POST:<could not parse>,
COOKIES:{'PHPSESSID': '4ee605dfadcf16c4995a2ccb01babee1',
 '__utma': '73719310.1015688273.1434490707.1434490707.1434490707.1',
 '__utmc': '73719310',
 '__utmz': '73719310.1434490707.1.1.utmccn=(direct)|utmcsr=(direct)|utmcmd=(none)',
 'csrftoken': 'N5ue70UyRYxHlJPMVHFtkf5Vo7zbbtGP',
 'sessionid': '77mjwz7o4licsix2br8if7ftubqp15fm'},
META:{'CONTENT_LENGTH': '323499',
 'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryS10vGylb60B4pY34',
 u'CSRF_COOKIE': u'N5ue70UyRYxHlJPMVHFtkf5Vo7zbbtGP',
 'DOCUMENT_ROOT': '/usr/share/nginx/html',
 'HTTPS': 'on',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_CACHE_CONTROL': 'max-age=0',
 'HTTP_CONTENT_LENGTH': '323499',
 'HTTP_CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryS10vGylb60B4pY34',
 'HTTP_COOKIE': 'PHPSESSID=4ee605dfadcf16c4995a2ccb01babee1; __utma=73719310.1015688273.1434490707.1434490707.1434490707.1; __utmc=73719310; __utmz=73719310.1434490707.1.1.utmccn=(direct)|utmcsr=(direct)|utmcmd=(none); sessionid=77mjwz7o4licsix2br8if7ftubqp15fm; csrftoken=N5ue70UyRYxHlJPMVHFtkf5Vo7zbbtGP',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'matik.strom.sk',
 'HTTP_ORIGIN': 'https://matik.strom.sk',
 'HTTP_REFERER': 'https://matik.strom.sk/sk/sutaze/semester/posledny/',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36',
 'PATH_INFO': u'/sk/priklady/odovzdaj/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '195.80.183.34',
 'REMOTE_PORT': '52001',
 'REQUEST_METHOD': 'POST',
 'REQUEST_URI': '/sk/priklady/odovzdaj/',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'matik.strom.sk',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.node': 'server.strom.sk',
 'uwsgi.version': '2.0.11.2',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f5be0718b70>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7f5bde773108>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>

**Comment by tbabej** [comment]
I believe this is just an incomplete request, i.e. see http://stackoverflow.com/questions/15544124/django-unreadableposterror-request-data-read-error

Maybe we should catch and log this, instead of letting it bubble through the whole framework?
